### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by LaserSlime** [FeatherMC/FeatherPlugin#1]
The last commit prevents this from compiling because theres a typo in the version number for the protocol definitions and version 1.2 of the api isn't in the repository (https://artifactory.feathermc.net/ui/native/feather-public/net/digitalingot/feather-server-api).

**Comment by paulzhng** [comment]
Fixed by https://github.com/FeatherMC/FeatherPlugin/commit/f21f55d47f39fbe3aa0c88849c41dfb901f474e6. Thanks for reporting!

**Comment by LaserSlime** [comment]
But version 1.2 of feather-api is still not in the repository.

**Comment by paulzhng** [comment]
This should be fixed now. Be aware this plugin is still very experimental and largely untested, feel free to try it out though.

**Comment by LaserSlime** [comment]
Yeah I noticed that. The bungeecord version currently kicks you if you try to connect. I think it's because the BungeeEventListener class isn't set as public, but I can't test it, because gradle won't let me use my custom test version of the api, because it keeps downloading the one from the online repository.
